//this file should be generated by script which should be run when a new custom icon is added to the project
export type IconList =
  | 'search'
  | 'inbox'
  | 'at'
  | 'assigned'
  | 'target-04'
  | 'calls'
  | 'hash'
  | 'chevron-left'
  | 'chevron-right'
  | 'contacts'
  | 'stats';

import search from '@/assets/icons/search.svg';
import inbox from '@/assets/icons/inbox.svg';
import calls from '@/assets/icons/calls.svg';
import contacts from '@/assets/icons/contacts.svg';
import hash from '@/assets/icons/hash-02.svg';
import target from '@/assets/icons/target-04.svg';
import assigned from '@/assets/icons/assigned.svg';
import chevronL from '@/assets/icons/chevron-left.svg';
import chevronR from '@/assets/icons/chevron-left.svg';
import at from '@/assets/icons/at-sign.svg';
import stats from '@/assets/icons/stats.svg';
import { ElementType } from 'react';

export const icons: Record<IconList, ElementType> = {
  search,
  inbox,
  hash,
  at,
  calls,
  'chevron-left': chevronL,
  'chevron-right': chevronR,
  assigned,
  contacts,
  'target-04': target,
  stats,
};
